# 'pirate' theme for SLiM by Simone Rota

msg_color               #b0b0c0
msg_font                Verdana:size=12:bold
msg_x                   30
msg_y                   30

background_style        tile

input_panel_x           50%
input_panel_y           45%
input_name_x            162
input_name_y            110
input_pass_x            162
input_pass_y            142
input_font          	Verdana:size=10
input_fgcolor           #b0b0c0
input_bgcolor           #111111
